name: Build & Deploy Latest App

on:
  push:
    branches:
      - main 

jobs:
  build:

    runs-on: macos-10.15

    steps:
      
    - uses: actions/checkout@master
    - name: Inject Prod Configuration
      run: ./inject-prod.sh ${{ secrets.MS_APP_CENTER_SECRET}} ${{ secrets.MS_APP_CENTER_URL_SCHEME }} ${{ secrets.PROD_ROOT_URL }} ${{ secrets.PROD_APP_NAME }} ${{ secrets.PROD_APP_BUNDLE_ID }}
    - name: Decrypt secrets
      run: ./decrypt-secrets.sh ${{ secrets.IOS_KEYS_SECRET }}
    - name: Clean & Build App
      run: ./build-app.sh
    - name: Create Archive
      run: ./archive-app.sh
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        check-latest: true
    - name: Install App Center CLI
      run: npm install -g appcenter-cli
    - name: Set up App Center context
      run: 
        appcenter login --token ${{ secrets.APP_CENTER_CLI_TOKEN }}
        appcenter apps set-current afterparty/afterparty-ios
    - name: Export Archive
      run: ./export-archive.sh
    - name: Upload Build
      run: "appcenter distribute release --file './AfterpartyProducts/Afterparty Prod.ipa' --group Collaborators"
    
